CUDA_VISIBLE_DEVICES=0,1 python OJT_yolo/yolo_ptln/train.py \
    --weights weights_t/best.pt \
    --cfg OJT_yolo/yolo_ptln/cfg/architecture/deyo.yaml \
    --hyp OJT_yolo/yolo_ptln/cfg/hyp/hyp.deyo.yaml \
    --data OJT_yolo/yolo_ptln/cfg/data/abjad.yaml \
    --name finetune_v9 \
    --batch 8 \
    --epochs 20 \
    --imgsz 640 \
    --device 0,1 \
    --workers 8 
